kind: pipeline
name: default
type: docker

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: registry.heroku.com/witty-bot/base
      registry: registry.heroku.com
      username:
        from_secret: heroku_email
      password:
        from_secret: heroku_api_key
      tags:
        - latest

  - name: deploy web
    image: plugins/docker
    settings:
      repo: registry.heroku.com/witty-bot/web
      dockerfile: Dockerfile.web
      build_args:
        - REGISTRY_URL=registry.heroku.com
      registry: registry.heroku.com
      username:
        from_secret: heroku_email
      password:
        from_secret: heroku_api_key
      tags:
        - ${DRONE_COMMIT_BRANCH}
        - latest
    depends_on: [build]

  - name: deploy worker
    image: plugins/docker
    settings:
      repo: registry.heroku.com/witty-bot/worker
      dockerfile: Dockerfile.worker
      build_args:
        - REGISTRY_URL=registry.heroku.com
      registry: registry.heroku.com
      username:
        from_secret: heroku_email
      password:
        from_secret: heroku_api_key
      tags:
        - ${DRONE_COMMIT_BRANCH}
        - latest
    depends_on: [build]

  - name: release
    image: alpine/httpie
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
    commands:
      - apk add docker
      - ./heroku-release.sh witty-bot web worker
    environment:
      HEROKU_AUTH_TOKEN:
        from_secret: heroku_auth_token

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock

trigger:
  branch: [main, ci]
  event: push
