# compose file for local development
version: '3'

services:
  web:
    container_name: witty-bot-web
    build:
      context: .
      args:
        SKIP_TEST: 1
    command: python web.py
    ports:
      - "8080:8080"
    environment:
      - APP_URL=http://0.0.0.0:8080
      - PORT=8080
      - TELEGRAM_BOT_TOKEN
      - GOOGLE_SERVICE_ACCOUNT_INFO
      - YANDEX_DISK_TOKEN
      - WOLFRAMALPHA_APP_ID

  worker:
    container_name: witty-bot-worker
    build:
      context: .
      args:
        SKIP_TEST: 1
    command: python -m bot
    environment:
      - PYTHONUNBUFFERED=1
      - APP_URL=http://web:8080
      - TELEGRAM_BOT_TOKEN
      - GOOGLE_SERVICE_ACCOUNT_INFO
      - YANDEX_DISK_TOKEN
      - WOLFRAMALPHA_APP_ID
