[tool.poetry]
name = "witty-bot"
version = "0.1.0"
description = ""
authors = ["Sergey Karatach <karatach1998@yandex.ru>"]

[tool.poetry.dependencies]
python = "3.7.9"
python-telegram-bot = "^13.1"
matplotlib = "^3.3"
sympy = "^1.7"
wolframalpha = "^4.1"
antlr4-python3-runtime = "^4.9"
PyPDF2 = "^1.26.0"
rutimeparser = "^1.1.1"
lxml = "^4.6.2"
requests = "^2.25.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
